### ISSUE TITLE
class instantiate and call function problem

### ISSUE THREAD

**Issue by yp2800** [b4ldr/racadm#2]
in main function add  

```
 racadm = Racadm('100.x.x.x', args.username, args.password,
          args.port )
  print racadm.get_session_info()

  racadm = Racadm(args.hostname, args.username, args.password,
          args.port )
  print racadm.get_session_info()
```

I got an error, I don't understand it. please help me! thanks~
root@master:~# python2.7  racadm.py -H  100.x.x.x -u root -p xxxxxx
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): 100.x.x.x
DEBUG:urllib3.connectionpool:Setting read timeout to None
DEBUG:urllib3.connectionpool:"POST /cgi-bin/login HTTP/1.1" 200 169
DEBUG:urllib3.connectionpool:Setting read timeout to None
DEBUG:urllib3.connectionpool:"POST /cgi-bin/exec HTTP/1.1" 200 426
INFO:racadm.Racadm:racadm getssninfo Successful
[{'date': datetime.datetime(2016, 10, 20, 18, 34, 14), 'ip': '172.16.0.16', 'type': 'RACADM', 'd': '79', 'user': 'root'}]
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): 100.64.2.11
DEBUG:urllib3.connectionpool:Setting read timeout to None
DEBUG:urllib3.connectionpool:"POST /cgi-bin/exec HTTP/1.1" 200 172
WARNING:racadm.Racadm:racadm getssninfo failed: ERROR: Session is not valid.
Traceback (most recent call last):
  File "getRacadmInfo.py", line 742, in <module>
    main()
  File "getRacadmInfo.py", line 739, in main
    print racadm.get_session_info()
  File "getRacadmInfo.py", line 435, in get_session_info
    results = self.basic_command('getssninfo')
  File "getRacadmInfo.py", line 220, in basic_command
    status, message = self._raw_command(command)
  File "getRacadmInfo.py", line 196, in _raw_command
    if not self.login():
  File "getRacadmInfo.py", line 149, in login
    content = self._get_response(uri, payload)
  File "getRacadmInfo.py", line 78, in _get_response
    response = self.session.post(uri, data=payload, verify=self.verify)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 497, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 421, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 359, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 289, in prepare
    self.prepare_cookies(cookies)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 486, in prepare_cookies
    cookie_header = get_cookie_header(self._cookies, self)
  File "/usr/lib/python2.7/dist-packages/requests/cookies.py", line 134, in get_cookie_header
    jar.add_cookie_header(r)
  File "/usr/lib/python2.7/cookielib.py", line 1326, in add_cookie_header
    attrs = self._cookie_attrs(cookies)
  File "/usr/lib/python2.7/cookielib.py", line 1285, in _cookie_attrs
    self.non_word_re.search(cookie.value) and version > 0):
TypeError: expected string or buffer

**Comment by b4ldr** [comment]
I see you have a pull request, where you able to resolve this or is it still an issue?
